export const clubs = [
  {
    id: 1,
    name: '编程协会',
    category: '科技',
    tags: ['编程', '开发', '竞赛', '开源'],
    description: '致力于编程技术交流与学习，定期举办编程马拉松和技术分享会。',
    memberCount: 156,
    recruitCount: 30,
    meetingTime: '每周三 19:00-21:00',
    location: '实验楼A301',
    requirements: ['对编程有热情', '有一颗学习的心'],
    image: '💻',
    personality: ['理性', '专注', '创新'],
    suitableMajors: ['计算机', '软件工程', '信息工程'],
    availableTime: ['周三晚', '周末']
  },
  {
    id: 2,
    name: '摄影协会',
    category: '文艺',
    tags: ['摄影', '剪辑', '艺术', '旅行'],
    description: '用镜头记录生活点滴，定期组织外拍活动和作品展览。',
    memberCount: 98,
    recruitCount: 25,
    meetingTime: '每周六 14:00-18:00',
    location: '艺术中心102',
    requirements: ['有相机或手机摄影爱好者', '热爱生活'],
    image: '📷',
    personality: ['感性', '审美', '创意'],
    suitableMajors: ['艺术设计', '新闻传播', '广告学'],
    availableTime: ['周末', '工作日下午']
  },
  {
    id: 3,
    name: '羽毛球社',
    category: '体育',
    tags: ['运动', '健康', '竞技', '团队'],
    description: '健康运动，快乐生活！为羽毛球爱好者提供交流平台。',
    memberCount: 203,
    recruitCount: 50,
    meetingTime: '每周二、四 18:00-20:00',
    location: '体育馆羽毛球馆',
    requirements: ['热爱运动', '身体健康'],
    image: '🏸',
    personality: ['活力', '开朗', '团队'],
    suitableMajors: ['所有专业'],
    availableTime: ['周二四晚', '周末']
  },
  {
    id: 4,
    name: '志愿者协会',
    category: '公益',
    tags: ['志愿', '公益', '服务', '爱心'],
    description: '传递爱心，服务社会，组织各类公益活动。',
    memberCount: 312,
    recruitCount: 80,
    meetingTime: '每月两次周六 9:00-17:00',
    location: '综合楼501',
    requirements: ['有爱心', '乐于助人', '时间充裕'],
    image: '❤️',
    personality: ['热情', '善良', '责任感'],
    suitableMajors: ['所有专业'],
    availableTime: ['周末', '灵活时间']
  },
  {
    id: 5,
    name: '辩论社',
    category: '学术',
    tags: ['辩论', '演讲', '逻辑', '表达'],
    description: '锻炼口才，提升逻辑思维，参与各类辩论赛事。',
    memberCount: 67,
    recruitCount: 20,
    meetingTime: '每周一、三 20:00-22:00',
    location: '教学楼B205',
    requirements: ['思维敏捷', '表达能力好'],
    image: '🎤',
    personality: ['理性', '逻辑', '表达'],
    suitableMajors: ['法学', '新闻', '中文', '政治'],
    availableTime: ['周一三晚', '周末']
  },
  {
    id: 6,
    name: '音乐社',
    category: '文艺',
    tags: ['音乐', '乐器', '演唱', '创作'],
    description: '音乐爱好者的聚集地，提供乐器教学和演出机会。',
    memberCount: 145,
    recruitCount: 35,
    meetingTime: '每周五 19:00-21:00',
    location: '艺术中心301',
    requirements: ['热爱音乐', '有基础更佳'],
    image: '🎵',
    personality: ['感性', '浪漫', '创意'],
    suitableMajors: ['音乐学', '艺术设计', '所有专业'],
    availableTime: ['周五晚', '周末']
  },
  {
    id: 7,
    name: '创业俱乐部',
    category: '实践',
    tags: ['创业', '商业', '创新', '投资'],
    description: '激发创业热情，培养商业思维，对接投资资源。',
    memberCount: 89,
    recruitCount: 25,
    meetingTime: '每周四 19:00-21:00',
    location: '创业大厦3楼',
    requirements: ['有创业想法', '或对创业感兴趣'],
    image: '🚀',
    personality: ['冒险', '创新', '执行'],
    suitableMajors: ['工商管理', '经济', '所有专业'],
    availableTime: ['周四晚', '周末']
  },
  {
    id: 8,
    name: '动漫社',
    category: '兴趣',
    tags: ['动漫', '绘画', 'COS', '游戏'],
    description: '二次元爱好者的天堂，组织漫展参观和COS活动。',
    memberCount: 178,
    recruitCount: 40,
    meetingTime: '每周日 14:00-18:00',
    location: '学生活动中心205',
    requirements: ['热爱ACG文化'],
    image: '🎭',
    personality: ['活泼', '创意', '热情'],
    suitableMajors: ['所有专业'],
    availableTime: ['周末']
  },
  {
    id: 9,
    name: '英语俱乐部',
    category: '学术',
    tags: ['英语', '口语', '留学', '交流'],
    description: '提升英语水平，拓展国际视野，模拟真实交流场景。',
    memberCount: 120,
    recruitCount: 30,
    meetingTime: '每周二、四 19:00-20:30',
    location: '外语楼102',
    requirements: ['想提升英语', '或准备留学'],
    image: '🌍',
    personality: ['开放', '勤奋', '国际'],
    suitableMajors: ['所有专业'],
    availableTime: ['周二四晚', '周末']
  },
  {
    id: 10,
    name: '篮球社',
    category: '体育',
    tags: ['篮球', '运动', '竞技', '团队'],
    description: '以球会友，切磋球技，代表学校参加各类比赛。',
    memberCount: 165,
    recruitCount: 40,
    meetingTime: '每周一、三、五 17:00-19:00',
    location: '篮球场',
    requirements: ['热爱篮球运动'],
    image: '🏀',
    personality: ['活力', '竞争', '团队'],
    suitableMajors: ['所有专业'],
    availableTime: ['工作日下午', '周末']
  },
  {
    id: 11,
    name: '棋类协会',
    category: '益智',
    tags: ['象棋', '围棋', '桌游', '策略'],
    description: '以棋会友，策略博弈，享受思考的乐趣。',
    memberCount: 56,
    recruitCount: 20,
    meetingTime: '每周六 15:00-18:00',
    location: '图书馆B2层',
    requirements: ['喜欢动脑', '热爱策略游戏'],
    image: '♟️',
    personality: ['沉稳', '思考', '策略'],
    suitableMajors: ['所有专业'],
    availableTime: ['周末', '工作日晚上']
  },
  {
    id: 12,
    name: '天文社',
    category: '学术',
    tags: ['天文', '观测', '宇宙', '科学'],
    description: '探索宇宙奥秘，定期组织星空观测活动。',
    memberCount: 42,
    recruitCount: 15,
    meetingTime: '每周五 20:00-22:00',
    location: '天文台/操场',
    requirements: ['对天文感兴趣', '能适应夜间活动'],
    image: '🔭',
    personality: ['好奇', '探索', '理性'],
    suitableMajors: ['物理', '天文', '所有专业'],
    availableTime: ['周五晚', '周末']
  }
];

export const questionnaire = {
  interests: [
    { id: 'tech', label: '科技创新', icon: '💡' },
    { id: 'art', label: '文化艺术', icon: '🎨' },
    { id: 'sports', label: '体育运动', icon: '⚽' },
    { id: 'social', label: '公益志愿', icon: '🤝' },
    { id: 'business', label: '创业商业', icon: '💼' },
    { id: 'academic', label: '学术研究', icon: '📚' },
    { id: 'entertainment', label: '娱乐休闲', icon: '🎮' },
    { id: 'media', label: '媒体传播', icon: '📺' }
  ],
  personality: [
    { id: 'rational', label: '理性逻辑型', description: '善于分析问题，注重逻辑推理' },
    { id: 'creative', label: '创意想象型', description: '富有想象力，喜欢新颖独特的事物' },
    { id: 'social', label: '社交活跃型', description: '喜欢与人交流，善于组织活动' },
    { id: 'steady', label: '沉稳内敛型', description: '脚踏实地，专注细节' },
    { id: 'adventurous', label: '冒险挑战型', description: '喜欢挑战，追求刺激' },
    { id: 'compassionate', label: '温暖关怀型', description: '富有同理心，热心助人' }
  ],
  majors: [
    '计算机/软件', '电子/通信', '机械/自动化', '土木/建筑',
    '经济/金融', '管理', '法律', '文学/语言',
    '艺术/设计', '新闻/传播', '生物/医学', '物理/化学',
    '数学', '外语', '哲学/历史', '其他'
  ],
  availableTime: [
    { id: 'weekday_morning', label: '工作日上午' },
    { id: 'weekday_evening', label: '工作日晚上' },
    { id: 'weekend_morning', label: '周末上午' },
    { id: 'weekend_afternoon', label: '周末下午' },
    { id: 'weekend_evening', label: '周末晚上' },
    { id: 'flexible', label: '时间灵活' }
  ],
  goals: [
    { id: 'skill', label: '提升技能', description: '学习专业技能，增强竞争力' },
    { id: 'social', label: '拓展人脉', description: '认识更多志同道合的朋友' },
    { id: 'interest', label: '发展兴趣', description: '培养兴趣爱好，丰富课余生活' },
    { id: 'resume', label: '丰富简历', description: '增加实践经验，提升就业竞争力' },
    { id: 'relax', label: '放松娱乐', description: '轻松愉快地度过课余时间' }
  ]
};
